#! /usr/bin/env python3

# --------------------------------------------------------------------
import sys, os, re, configparser as cp, tempfile, shutil, fnmatch
import subprocess as sp

# --------------------------------------------------------------------
ROOT = os.path.dirname(__file__)

ACHECKER = os.path.join(
    ROOT, *'../upload/autocorrect/scripts/achecker.py'.split('/'))

LIBSUPPORT = os.path.join(
    ROOT, *'../upload/autocorrect/libsupport'.split('/'))

# --------------------------------------------------------------------
class Object(object):
    def __init__(self, **kw):
        super().__init__()
        self.__dict__.update(kw)

# --------------------------------------------------------------------
class Error(Exception):
    pass

# --------------------------------------------------------------------
def read_file(path, charset = None):
    mode = 'rb' if charset is None else 'r'
    try:
        with open(path, mode, encoding = charset) as stream:
            return stream.read()
    except (IOError, UnicodeDecodeError) as e:
        raise Error("error while reading file `%s': %s" % (path, e), e)

# --------------------------------------------------------------------
ASECTION = 'assignment'
CSECTION = 'auto-correct'

def read_options(filename):
    config = cp.ConfigParser()
    config.read_string(read_file(filename, 'utf-8'))

    options = Object()

    try:
        options.subcode = config.get(ASECTION, 'subcode')
        options.dir     = config.get(CSECTION, 'dir'    )
        options.implem  = config.get(CSECTION, 'implem' )
        options.forno   = config.get(CSECTION, 'forno'  ).split()
        options.extra   = config.get(CSECTION, 'extra'  ).split()
        options.map     = []

        fmaps = config.get(ASECTION, 'map', fallback = '').split()
        for fmap in fmaps:
            if ':' not in fmap:
                continue
            options.map.append(fmap.split(':', 2))

    except cp.Error as e:
        raise Error('cannot read INI file (%s): %s' % (filename, e), e)

    return options

# --------------------------------------------------------------------
def filemap(fmaps, filename):
    for ptn, dst in fmaps:
        if fnmatch.fnmatch(filename, ptn):
            return os.path.join(*(dst.split('/') + [filename]))
    return filename

# --------------------------------------------------------------------
def _main():
    if len(sys.argv)-1 < 1:
        print('Usage: %s [TD.ini] <INDEX...>' % (sys.argv[0],))
        exit(1)

    inifile = sys.argv[1]
    index   = sys.argv[2:]
    options = read_options(inifile)
    index   = index or options.forno

    for qno in index:
        tfile = 'Test_%s_%s.java' % (options.subcode, qno)
        with tempfile.TemporaryDirectory() as tmppath:
            libpath  = os.path.join(tmppath, 'lib' )
            srcpath  = os.path.join(tmppath, 'src' )
            testpath = os.path.join(tmppath, 'test')

            shutil.copytree(LIBSUPPORT, libpath)
            os.makedirs(srcpath); os.makedirs(testpath)
            for filename in options.extra:
                os.makedirs(
                    os.path.join(testpath, os.path.dirname(filename)),
                    exist_ok = True)
                shutil.copy(os.path.join(options.dir, filename),
                            os.path.join(testpath, filename))
            shutil.copy(os.path.join(options.dir, tfile), srcpath)
            implem = os.listdir(options.implem)
            implem = [x for x in implem if \
                          os.path.isfile(os.path.join(options.implem, x))]
            implem = [x for x in implem if os.path.splitext(x)[1] == '.java']
            for filename in implem:
                fullname = os.path.join(options.implem, filename)
                dstname  = os.path.join(srcpath, filemap(options.map, filename))
                contents = read_file(fullname, 'utf-8')
                contents = re.sub(r'^\s*//#', '#', contents, 0, re.M)
                with tempfile.NamedTemporaryFile() as tmpfile:
                    tmpfile.write(contents.encode('utf-8')); tmpfile.flush()
                    os.makedirs(os.path.dirname(dstname), exist_ok = True)
                    sp.check_call(
                        ['gpp', '-C', '-o', dstname, '-DQ=%s' % (qno,), tmpfile.name])
            sp.check_call([ACHECKER, tmppath, os.path.splitext(tfile)[0]])

# --------------------------------------------------------------------
if __name__ == '__main__':
    _main()
